### ISSUE TITLE
Steam flatpak does not start with gtk enabled

### ISSUE THREAD

**Issue by codebam** [danth/stylix#1093]
A typical log looks like:
```
✦ ❯ com.valvesoftware.Steam
bwrap: Can't make symlink at /home/codebam/.themes/adw-gtk3: existing destination is ../../../nix/store/wf71q57bq0lv5q3jmal08lx2vh5mn9br-home-manager-files/.themes/adw-gtk3
```

**Comment by codebam** [comment]
Removing this file allows steam to start, or disabling the gtk target

**Comment by trueNAHO** [comment]
For reference, Flatpak support was added in commit 963e77a3a4fc ("gtk: add support for theming Flatpak applications (#693)"). Although, https://github.com/danth/stylix/pull/696 does not implement Flatpak support, it also patches Steam and may be vaguely related.

Cc: @brckd

**Comment by brckd** [comment]
It's probably a Flatpak related issue, because my Steam app from Nixpkgs works fine. The `gtk.flatpakSupport` option in Stylix overrides `.themes/adw-gtk3`, so disabling it seems to be the only solution for now. I might add an option to disable it for individual Flatpaks in the future.

I also wonder why the Flatpak version tries to override that theme in the first place, since Steam doesn't use GTK. It might be useful to check what dependencies the Steam Flatpak installs.

**Comment by codebam** [comment]
This was fixed

**Comment by brckd** [comment]
Nice! Do you know what fixed it?

**Comment by dafitt** [comment]
I'm on unstable (25.11) freshly updated today 2025-06-01, but the problem is still persisting.
I'm also using the nixos stylix module, so that can't be it.

**Comment by dafitt** [comment]
Here is more information, why that happens: https://github.com/flathub/com.valvesoftware.Steam/issues/66
What i could read, because of `--persist=.` which is the default for now.
