### ISSUE TITLE
Hyprland decoration:shadow:color does not exist

### ISSUE THREAD

**Issue by drnfc** [danth/stylix#689]
I'm getting the following error:  config option <decoration:shadow:color> does not exist.
![20241219_19h50m58s_grim](https://github.com/user-attachments/assets/b13899d2-4218-457a-95fe-13dfaa4a2f3d)

**Comment by trueNAHO** [comment]
This Hyprland and Stylix version mismatch is already resolved by https://github.com/danth/stylix/pull/610. Consider keeping both dependencies in sync or simply updating both.

**Comment by drnfc** [comment]
Huh, I updated my dependencies yesterday.  It's still not working for me, but I guess it's good to know the issue is on my end.

**Comment by danth** [comment]
Make sure you're using either:

- Stylix `master` + NixOS `nixos-unstable` + Home Manager `master`
- Stylix `release-24.11` + NixOS `nixos-24.11` + Home Manager `release-24.11`
